### ISSUE TITLE
.pbp download incomplete

### ISSUE THREAD

**Issue by LameNobody** [Freakler/vita-AdrenalineEasyInstaller#10]
while installing latest version, my device went to sleep while downloading the pbp.
it said complete and rebooted the device
and upon running adrenaline, the pbp was not found

possible fix:
check if download successful, maybe verify size/checksum

Add option to check for missing files, or repair installations?
(the application considered the latest version installed, and wouldn't allow re-installation of the latest version)

**Comment by Freakler** [comment]
Everything you just mentioned is there..
https://github.com/Freakler/vita-AdrenalineEasyInstaller/blob/master/main.c#L360
