### ISSUE TITLE
Can't install on PS Vita with FW 3.60

### ISSUE THREAD

**Issue by Kinc4id** [Freakler/vita-AdrenalineEasyInstaller#11]
I tried to install this on my Vita with FW 3.6  but the installer says:

Model = PlaystationTV
Enter Button = X
Firmware = Error!?
!! This firmware version may not be supported !!

I can continue or exit but I worry that it might break something and I won't be able to install FW 3.6 again. Is this a known issue? Did I miss something?

**Comment by Freakler** [comment]
are you using the latest version? you probably have 'unsafe homebrew' disabled?

**Comment by Kinc4id** [comment]
Damn, you are right. I had unsafe homebrew disabled. I was sure I actived it before and didn't check again. Sorry to bother you. :-/
