### ISSUE TITLE
could not correct emulate some game

### ISSUE THREAD

**Issue by fantasynoff** [Freakler/vita-AdrenalineEasyInstaller#12]
title: Tengai Makyou The Apocalypse IV
M33/NP/Inf 3 loader all tested, every FMV just show black screen, but sound is ok.

this is a special game even the emulator on pc still could not 100% work with no error :(

can you fix that? thanks.

**Comment by Freakler** [comment]
I am not the creator of Adrenaline..

**Comment by fantasynoff** [comment]
sorry :(

reposted to TheOfficialFloW issue.
