### ISSUE TITLE
Does not work with Sd card mounted. 

### ISSUE THREAD

**Issue by a7mag3ddon** [Freakler/vita-AdrenalineEasyInstaller#13]
As topic really, with Hankaku Enso installed along with an SD card mounted as UX0:/ adrenaline does not load.

**Comment by bbrink68** [comment]
From another issue:

> Your config.txt should be on ur0: if you're using any ux0: remounting plugin - delete ux0:tai/config.txt.
> 
> Make sure it looks like this:
> 
> *KERNEL
> ur0:tai/gamesd.skprx
> ux0:tai/adrenaline.skprx
> The line order is the important part. If adrenaline.skprx is first, it will attempt to load off the vita memory card and subsequently fail, since ux0: is not yet redirected.

**Comment by a7mag3ddon** [comment]
Works ok. You have to make sure adrenaline loads AFTER gamesd in kernal section.
