### ISSUE TITLE
AdrenalineEasyInstaller stops at failed activation check, although not necessary anymore for 6.61

### ISSUE THREAD

**Issue by windsurfer1122** [Freakler/vita-AdrenalineEasyInstaller#14]
AdrenalineEasyInstaller v1.15 for Adrenaline v6.61 stops at failed activation check, although this is not necessary anymore for latest Adrenaline v6.61-6_fix.

```
...
Checking for tm0:npdrm/act.dat file.. Not found!!

!!! You must activate your Vita first !!!
Press X to exit...
```

**Comment by Freakler** [comment]
of course.. this installer is only for adrenaline versions up to 5.1 which do need the activation.

**Comment by windsurfer1122** [comment]
Ok, than the README.md of this repository is irritating, as it says "An EasyInstaller for the **6.61** Adrenaline eCFW by TheFloW".
Would it be too difficult to update the EasyInstaller for 6.61?

**Comment by Freakler** [comment]
Adrenaline is and always was 6.61 based..

and no but it makes no sense anymore as the newest version(s) come in VPK format already - noob proof

**Comment by windsurfer1122** [comment]
Ok. Wanted to use the EasyInstaller to get all files like EBOOT.PBP plus renaming, etc.
Thanks for your time.
