### ISSUE TITLE
Tai v8 PSTV with USB memory card

### ISSUE THREAD

**Issue by erfg12** [Freakler/vita-AdrenalineEasyInstaller#2]
For some reason, EasyInstaller shows my PSP game (Petz Saddle Club Demo), but when I press X everything is green and says press X to restart. 

After restarting doesn't show Adrenaline and launching the PSP demo just starts the demo like normal.

**Comment by fatiianywhere** [comment]
Hi,same thing happened to me,too.Is there any solition to fix this?

**Comment by erfg12** [comment]
Apparently you have to remove the USB thumbstick, install adrenaline and psp demo to system memory, FTP in to the system and transfer pspemu folder off. Then mount the USB thumbdrive, FTP into system again, transfer pspemu to uma0, mount USB thumbdrive as ux0. Now you're ready.

**Comment by Freakler** [comment]
yes don't use the installer in combination with the USb stick feature. The reboot + update database will restore everything found on the real memory card and update it in app.db. Once again: Once there is a way to manually trigger the database update via some function this will be no problem anymore

**Comment by Sir-Charles** [comment]
The "app DB tool" has a way to update database rather than rebuild, and a way to save icon layout.

**Comment by Freakler** [comment]
> The "app DB tool" has a way to update database rather than rebuild, and a way to save icon layout.

it uses exactly my method.. and no one said anything about rebuilding?!

**Comment by CelesteBlue-dev** [comment]
Freakler, is luck's DB rebuilder/updatet from GekiHEN contest adding something new ?
