### ISSUE TITLE
Waste reboot

### ISSUE THREAD

**Issue by Yoti** [Freakler/vita-AdrenalineEasyInstaller#3]
Why you force to reboot if there is no 661.PBP and no internet connection? Better just close program.

**Comment by Luro02** [comment]
you could just press the Homebutton ;)

**Comment by Freakler** [comment]
reboot is currently necessary to make the pboot take effect until there is a better way. We couldn't get scePromoterUtilityPromoteBackup to work but there probably is a livearea function for that. For now its the only way to trigger the update database. I know it sucks.. :/
