### ISSUE TITLE
impossible to re-install henkaku after adrenaline easyinstaller v110 installed

### ISSUE THREAD

**Issue by Rebolon** [Freakler/vita-AdrenalineEasyInstaller#8]
The install of adrenaline has been done with Lemmings game
It reboot the console
Then i have to install again henkaku (as usual after a reboot) but it fails.
So the console is no more hacked...

 * moonshell or vistashell cannot be launched and give the error C1-6775-5
 * adrenaline bubble give the error C1-2858-3

What should i do ? is there a way to flash the console again ? or to reset the console to be able to restart the henkaku hack ?

**Comment by Freakler** [comment]
its a henkaku problem. nothing I can do
But i guess you figured something out by now

**Comment by Rebolon** [comment]
yep hard-reset the console and reinstall.
thx
